apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
- node-problem-detector.yaml
configMapGenerator:
- name: node-problem-detector-custom-config
  files:
  - ./config/custom-plugin-monitor.json
- name: node-problem-detector-custom-plugin
  files:
  - ./config/plugin/check_up_file.sh
